"""Add username column to user table

Revision ID: add_username_column
Revises: 3d1249678e37
Create Date: 2025-07-13 03:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_username_column'
down_revision = '3d1249678e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add username column as nullable first
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
    
    # Update existing users with a default username based on email
    op.execute("UPDATE user SET username = SUBSTR(email, 1, INSTR(email, '@') - 1) WHERE username IS NULL")
    
    # Make username column non-nullable and unique
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.create_unique_constraint('uq_user_username', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_column('username')
    # ### end Alembic commands ###